# #c("8TRA.ST","AAK.ST","ABB.ST","ADDT-B.ST","AF-B.ST","ALFA.ST","ALIV-SDB.ST","AM1S.ST","ARION-SDB.ST","ARJO-B.ST","ASSA-B.ST","ATCO-A.ST","ATCO-B.ST","ATRLJ-B.ST","ATT.ST","AXFO.ST","AZA.ST","AZN.ST","BALD-B.ST","BEIJ-B.ST","BETS-B.ST","BILL.ST","BOL.ST","BONAV-A.ST","BONAV-B.ST","BRAV.ST","CAST.ST","DOM.ST","EKTA-B.ST","ELUX-A.ST","ELUX-B.ST","EPI-A.ST","EPI-B.ST","EQT.ST","ERIC-A.ST","ERIC-B.ST","ESSITY-A.ST","ESSITY-B.ST","EVO.ST","FABG.ST","FOI-B.ST","GETI-B.ST","HEMF.ST","HEMF-PREF.ST","HEXA-B.ST","HM-B.ST","HOLM-A.ST","HOLM-B.ST","HPOL-B.ST","HUFV-A.ST","HUFV-C.ST","HUSQ-A.ST","HUSQ-B.ST","ICA.ST","INDT.ST","INDU-A.ST","INDU-C.ST","INTRUM.ST","INVE-A.ST","INVE-B.ST","JM.ST","KIND-SDB.ST","KINV-A.ST","KINV-B.ST","KLED.ST","KLOV-A.ST","KLOV-B.ST","KLOV-PREF.ST","LATO-B.ST","LIFCO-B.ST","LOOM-B.ST","LUMI.ST","LUND-B.ST","LUPE.ST","MTG-A.ST","MTG-B.ST","MTRS.ST","NCC-A.ST","NCC-B.ST","NDA-SE.ST","NENT-A.ST","NENT-B.ST","NET-B.ST","NIBE-B.ST","NOBI.ST","NOLA-B.ST","NYF.ST","PEAB-B.ST","PNDX-B.ST","RATO-A.ST","RATO-B.ST","RESURS.ST","SAAB-B.ST","SAGA-A.ST","SAGA-B.ST","SAGA-D.ST","SAGA-PREF.ST","SAND.ST","SBB-B.ST","SBB-D.ST","SCA-A.ST","SCA-B.ST","SEB-A.ST","SEB-C.ST","SECU-B.ST","SHB-A.ST","SHB-B.ST","SKA-B.ST","SKF-A.ST","SKF-B.ST","SOBI.ST","SSAB-A.ST","SSAB-B.ST","STE-A.ST","STE-R.ST","SWEC-A.ST","SWEC-B.ST","SWED-A.ST","SWMA.ST","TEL2-A.ST","TEL2-B.ST","TELIA.ST","THULE.ST","TIETOS.ST","TIGO-SDB.ST","TREL-B.ST","VITR.ST","VNE-SDB.ST","VOLV-A.ST","VOLV-B.ST","WALL-B.ST","WIHL.ST","ACAD.ST","ADAPT.ST","ALIF-B.ST","ALIG.ST","AMBEA.ST","ANOD-B.ST","AOI.ST","AQ.ST","ATORX.ST","BEIA-B.ST","BERG-B.ST","BESQ.ST","BETCO.ST","BHG.ST","BILI-A.ST","BIOA-B.ST","BIOG-B.ST","BIOT.ST","BMAX.ST","BOOZT.ST","BTS-B.ST","BUFAB.ST","BULTEN.ST","BURE.ST","CALTX.ST","CAMX.ST","CAT-A.ST","CAT-B.ST"); 

utveckling <- c()
kopta <- data.frame(list(1,2))
colnames(kopta) <- c('company','date')
money <- 1000
a <- 0
invested <- data.frame(list('hej',2,TRUE, 2))
colnames(invested) <- c('company','money', 'return',"development")
invested_clone <- data.frame(list('hej',2,TRUE, 2))
colnames(invested_clone) <- c('company','money', 'return',"development")

me <- list()

track_global <- list()
track_common <- list()

new_companies <- c();
new_companies2 <- c();
count <- 0

library("fPortfolio")
library("timeSeries")
library('tseries')
library('PerformanceAnalytics')
library(lubridate)
library('dplyr')
library('TTR')

require('mongolite'); 
con <- mongo("stocks", url = "mongodb://localhost:27017/stocks"); 
#the_date <- "2019-11-01"
#startdate1 <- "2015-01-01"; 
#enddate1 <- the_date; 
#"AES","ADI","ANTM","BLL","BBT","BBY","CAH","STZ","GLW","DG","EMR","GIS","GT","HBI","HCP","HLT","IVZ","IPGP","JBHT","MAR","MSFT","NTAP","NKE","NOC","PCAR","PYPL","PLD","ROP","SBAC","SWKS","TDG","UAL","VTR","VRSN","WYNN","XLNX","YUM","AMZN","AXP","APTV","HRB","KMX","CNC","SCHW","COP","CSX","ETFC","EA","EOG","FFIV","FITB","FLIR","HD","IDXX","ILMN","NOV","NFLX","NSC","OXY","PKG","SPGI","CRM","STT","TTWO","ULTA","VLO","ACN","AMD","ALLE","AMP","DE","FLS","HOG","JEC","MRO","MKC","COO","MOS","TSCO","ABT","ABBV","AYI","AIG","BAX","CBOE","CTSH","DHI","EBAY","GM","HPQ","JCI","MTD","MCO","OKE","PH","PRGO","PVH","RTN","SPG","SYMC","TPR"

# THE COMPANIES
#"MMM","AOS","ABT","ABBV","ACN","ATVI","AYI","ADBE","AAP","AMD","AES","AET","AMG","AFL","A","APD","AKAM","ALK","ALB","ARE","ALXN","ALGN","ALLE","AGN","ADS","LNT","ALL","GOOGL","GOOG","MO","AMZN","AEE","AAL","AEP","AXP","AIG","AMT","AWK","AMP","ABC","AME","AMGN","APH","APC","ADI","ANDV","ANSS","ANTM","AON","APA","AIV","AAPL","AMAT","APTV","ADM","ARNC","AJG","AIZ","T","ADSK","ADP","AZO","AVB","AVY","BHGE","BLL","BAC","BAX","BBT","BDX","BRK.B","BBY","BIIB","BLK","HRB","BA","BKNG","BWA","BXP","BSX","BHF","BMY","AVGO","BF.B","CHRW","CA","COG","CDNS","CPB","COF","CAH","KMX","CCL","CAT","CBOE","CBRE","CBS","CELG","CNC","CNP","CTL","CERN","CF","SCHW","CHTR","CVX","CMG","CB","CHD","CI","XEC","CINF","CTAS","CSCO","C","CFG","CTXS","CME","CMS","KO","CTSH","CL","CMCSA","CMA","CAG","CXO","COP","ED","STZ","GLW","COST","COTY","CCI","CSRA","CSX","CMI","CVS","DHI","DHR","DRI","DVA","DE","DAL","XRAY","DVN","DLR","DFS","DISCA","DISCK","DISH","DG","DLTR","D","DOV","DWDP","DPS","DTE","DUK","DRE","DXC","ETFC","EMN","ETN","EBAY","ECL","EIX","EW","EA","EMR","ETR","EVHC","EOG","EQT","EFX","EQIX","EQR","ESS","EL","RE","ES","EXC","EXPE","EXPD","ESRX","EXR","XOM","FFIV","FB","FAST","FRT","FDX","FIS","FITB","FE","FISV","FLIR","FLS","FLR","FMC","FL","F","FTV","FBHS","BEN","FCX","GPS","GRMN","IT","GD","GE","GGP","GIS","GM","GPC","GILD","GPN","GS","GT","GWW","HAL","HBI","HOG","HRS","HIG","HAS","HCA","HCP","HP","HSIC","HES","HPE","HLT","HOLX","HD","HON","HRL","HST","HPQ","HUM","HBAN","HII","IDXX","INFO","ITW","ILMN","INCY","IR","INTC","ICE","IBM","IP","IPG","IFF","INTU","ISRG","IVZ","IPGP","IQV","IRM","JBHT","JEC","SJM","JNJ","JCI","JPM","JNPR","KSU","K","KEY","KMB","KIM","KMI","KLAC","KSS","KHC","KR","LB","LLL","LH","LRCX","LEG","LEN","LUK","LLY","LNC","LKQ","LMT","L","LOW","LYB","MTB","MAC","M","MRO","MPC","MAR","MMC","MLM","MAS","MA","MAT","MKC","MCD","MCK","MDT","MRK","MET","MTD","MGM","KORS","MCHP","MU","MSFT","MAA","MHK","TAP","MDLZ","MON","MNST","MCO","MS","MSI","MYL","NDAQ","NOV","NAVI","NKTR","NTAP","NFLX","NWL","NFX","NEM","NWSA","NWS","NEE","NLSN","NKE","NI","NBL","JWN","NSC","NTRS","NOC","NCLH","NRG","NUE","NVDA","ORLY","OXY","OMC","OKE","ORCL","PCAR","PKG","PH","PAYX","PYPL","PNR","PBCT","PEP","PKI","PRGO","PFE","PCG","PM","PSX","PNW","PXD","PNC","RL","PPG","PPL","PX","PFG","PG","PGR","PLD","PRU","PEG","PSA","PHM","PVH","QRVO","QCOM","PWR","DGX","RRC","RJF","RTN","O","RHT","REG","REGN","RF","RSG","RMD","RHI","ROK","COL","ROP","ROST","RCL","SPGI","CRM","SBAC","SCG","SLB","STX","SEE","SRE","SHW","SPG","SWKS","SLG","SNA","SO","LUV","SWK","SBUX","STT","SRCL","SYK","STI","SIVB","SYMC","SYF","SNPS","SYY","TROW","TTWO","TPR","TGT","TEL","FTI","TXN","TXT","BK","CLX","COO","HSY","MOS","TRV","DIS","TMO","TIF","TWX","TJX","TMK","TSS","TSCO","TDG","TRIP","FOXA","FOX","TSN","USB","UDR","ULTA","UAA","UA","UNP","UAL","UNH","UPS","URI","UTX","UHS","UNM","VFC","VLO","VAR","VTR","VRSN","VRSK","VZ","VRTX","VIAB","V","VNO","VMC","WMT","WBA","WM","WAT","WEC","WFC","WELL","WDC","WU","WRK","WY","WHR","WMB","WLTW","WYN","WYNN","XEL","XRX","XLNX","XL","XYL","YUM","ZBH","ZION","ZTS",
#"TWTR","ABMD","FTNT","AEIS","AGCO","MDRX","AABA","AMCX","ASML","LBTYA","NTES","SIRI","WDAY","APPS","INS","GSB","CHMA","BRID","NSTG","IDN","HYGS","ZYXI","SLP","SHOP","CYBR","RPD","TLRA","PRO","MAN","KTOS","QSR","DDS","CRBP","CASY","TPX","HUBS","JCP","ANET","RS","DCI","HLF","DK","IBKR","TAL","RIG","CDW","URBN","NVR","DLPH","ZYNE","GNC","DF","MMYT","BABA","TPC","EPC","PE","FLT","AKRX","JAZZ","LIN","OI","EAT","SBNY","SGEN","NEWR","INT","EPD","MDU","ZAYO","CLMT","SPN","AMTD","VST","CCEP","ENB","SU","LM","MRVL","BTI","SNE","VMW","IONS","AVT","WLK","RMAX","LAMR","DELL","TRU","SHAK","TX","CVA","BYND","CHWY","SEDG","CIT","SIX","NOW","YNDX","BITA","BC","HDS","BURL","MXIM","CE","LITE","ATO","MIK","DB","SON","SQ","CHL","BLMN","OC","WEN","ON","GWPH","GRA","TMUS","BUD","CTRP","MOMO","TRGP","CRI","EVRG","MELI","BX","LULU","LBTYK","ELAN","MOH","SNAP","KKR","WBC","CFX","SERV","LYFT","CRON","ARGO","LW","COMM","GHC","OMI","WAB","OLED","QRTEA","RACE","RPM","CACC","EDU","NTLA","RNR","SANM","PAGP","TEVA","UNIT","CHDN","CZR","VIPS","H","SCI","SGMO","WUBA","ANDE","OUT","VSM"

#the filtrered companies
c_companies <- c("AES","ADI","ANTM","BLL","BBT","BBY","CAH","STZ","GLW","DG","EMR","GIS","GT","HBI","HCP","HLT","IVZ","IPGP","JBHT","MAR","MSFT","NTAP","NKE","NOC","PCAR","PYPL","PLD","ROP","SBAC","SWKS","TDG","UAL","VTR","VRSN","WYNN","XLNX","YUM","AMZN","AXP","APTV","HRB","KMX","CNC","SCHW","COP","CSX","ETFC","EA","EOG","FFIV","FITB","FLIR","HD","IDXX","ILMN","NOV","NFLX","NSC","OXY","PKG","SPGI","CRM","STT","TTWO","ULTA","VLO","ACN","AMD","ALLE","AMP","DE","FLS","HOG","JEC","MRO","MKC","COO","MOS","TSCO","ABT","ABBV","AYI","AIG","BAX","CBOE","CTSH","DHI","EBAY","GM","HPQ","JCI","MTD","MCO","OKE","PH","PRGO","PVH","RTN","SPG","SYMC","TPR","AAP","GOOGL","GOOG","AMAT","ADP","BIIB","BSX","COG","CERN","CF","CI","CINF","DRI","FAST","FL","GE","HAS","INCY","ISRG","KSS","KHC","M","MPC","MDT","MGM","MS","NAVI","NEM","NUE","ORLY","PHM","REG","REGN","ROST","UNM","VNO","AAPL","JNJ","V","DIS","VZ","KO","BA","INTC","IBM","MMM");
test2 <- c("CATE.ST","CCC.ST","CEVI.ST","CLA-B.ST","CLAS-B.ST","COIC.ST","COLL.ST","COOR.ST","CORE-A.ST","CORE-B.ST","CORE-PREF.ST","CRED-A.ST","CTM.ST","DIOS.ST","DUNI.ST","DUST.ST","EAST.ST","ELAN-B.ST","ELTEL.ST","ENEA.ST","ENG.ST","ENQ.ST","FAG.ST","FING-B.ST","FNM.ST","FPAR.ST","FPAR-PREF.ST","G5EN.ST","GARO.ST","GIGSEK.ST","GRNG.ST","GUNN.ST","HANDI.ST","HEBA-B.ST","HEM-B.ST","HIQ.ST","HLDX.ST","HMS.ST","HNSA.ST","HOFI.ST","HTRO.ST","HUM.ST","IAR-B.ST","IBT-B.ST","IMMNOV.ST","INSTAL.ST","INWI.ST","IPCO.ST","ITAB-B.ST","IVSO.ST","JOMA.ST","JOSE.ST","K2A-B.ST","K2A-PREF.ST","KABE-B.ST","KAR.ST","KARO.ST","KNOW.ST","LAGR-B.ST","LEO.ST","LIAB.ST","LUC.ST","LUG.ST","MAG.ST","MCOV-B.ST","MEKO.ST","MIPS.ST","MMGR-B.ST","MSON-A.ST","MSON-B.ST","MYCR.ST","NETI-B.ST","NEWA-B.ST","NMAN.ST","NOBINA.ST","NP3.ST","NP3-PREF.ST","NWG.ST","OASM.ST","OEM-B.ST","ONCO.ST","OP.ST","OP-PREF.ST","OP-PREFB.ST","OPUS.ST","ORES.ST","ORX.ST","PACT.ST","PLAZ-B.ST","PROB.ST","QLINEA.ST","QLRO.ST","RAY-B.ST","RECI-B.ST","SAS.ST","SCST.ST","SECT-B.ST","SHOT.ST","SINCH.ST","SKIS-B.ST","SMF.ST","SRNKE-B.ST","STAR-A.ST","STAR-B.ST","STEF-B.ST","SVOL-A.ST","SVOL-B.ST","SWOL-B.ST","SYSR.ST","TETY.ST","TFBANK.ST","TOBII.ST","TRAC-B.ST","TROAX.ST","VBG-B.ST","VIT-B.ST","VNV-SDB.ST","VOLO.ST","VOLO-PREF.ST","XANO-B.ST","XVIVO.ST","ACE.ST","ACTI.ST","AGRO.ST","ANOT.ST","ARISE.ST","ARP.ST","ATIC.ST","ATRE.ST","B3.ST","BACTI-B.ST","BALCO.ST","BEGR.ST","BELE.ST","BINV.ST","BONEX.ST","BONG.ST","BORG.ST","BOUL.ST","BRG-B.ST","BRIN-B.ST","CANTA.ST","CBTT-B.ST","CCOR-B.ST","CONS-B.ST","CRAD-B.ST","CTT.ST","DEDI.ST","DORO.ST","DURC-B.ST","EDGE.ST","ELEC.ST","ELOS-B.ST","EMPIR-B.ST","ENDO.ST","ENRO.ST","ENRO-PREF.ST","EOLU-B.ST","EPIS-B.ST","ETX.ST","EWRK.ST","FEEL.ST","FMM-B.ST","FPIP.ST","GHP.ST","GREEN.ST","HANZA.ST","HAV-B.ST","ICTA.ST","IMMU.ST","IS.ST","KDEV.ST","LAMM-B.ST","LIME.ST","MCAP.ST","MEAB-B.ST","MIDW-A.ST","MIDW-B.ST","MOB.ST","MOMENT.ST","MQ.ST","MSAB-B.ST","MULQ.ST","MVIR-B.ST","NAXS.ST","NCAB.ST","NGS.ST","NIL-B.ST","NOTE.ST","NTEK-B.ST","NVP.ST","ODD.ST","ORTI-A.ST","ORTI-B.ST","PENG-B.ST","PLED.ST","POOL-B.ST","PREC.ST","PREV-B.ST","PRIC-B.ST","PROF-B.ST","RAIL.ST","REJL-B.ST","RNBS.ST","RROS.ST","SANION.ST","SEMC.ST","SENS.ST","SINT.ST","SOF-B.ST","SPOR.ST","SSM.ST","STRAX.ST","STWK.ST","SVED-B.ST","SVIK.ST","TRAD.ST","TRENT.ST","VICO.ST","VRG-B.ST","VSSAB-B.ST","WISE.ST","XBRANE.ST","ZETA.ST")

test <- c("8TRA.ST","AAK.ST","ABB.ST","ADDT-B.ST","AF-B.ST","ALFA.ST","ALIV-SDB.ST","AM1S.ST","ARION-SDB.ST","ARJO-B.ST","ASSA-B.ST","ATCO-A.ST","ATCO-B.ST","ATRLJ-B.ST","ATT.ST","AXFO.ST","AZA.ST","AZN.ST","BALD-B.ST","BEIJ-B.ST","BETS-B.ST","BILL.ST","BOL.ST","BONAV-A.ST","BONAV-B.ST","BRAV.ST","CAST.ST","DOM.ST","EKTA-B.ST","ELUX-A.ST","ELUX-B.ST","EPI-A.ST","EPI-B.ST","EQT.ST","ERIC-A.ST","ERIC-B.ST","ESSITY-A.ST","ESSITY-B.ST","EVO.ST","FABG.ST","FOI-B.ST","GETI-B.ST","HEMF.ST","HEMF-PREF.ST","HEXA-B.ST","HM-B.ST","HOLM-A.ST","HOLM-B.ST","HPOL-B.ST","HUFV-A.ST","HUFV-C.ST","HUSQ-A.ST","HUSQ-B.ST","ICA.ST","INDT.ST","INDU-A.ST","INDU-C.ST","INTRUM.ST","INVE-A.ST","INVE-B.ST","JM.ST","KIND-SDB.ST","KINV-A.ST","KINV-B.ST","KLED.ST","KLOV-A.ST","KLOV-B.ST","KLOV-PREF.ST","LATO-B.ST","LIFCO-B.ST","LOOM-B.ST","LUMI.ST","LUND-B.ST","LUPE.ST","MTG-A.ST","MTG-B.ST","MTRS.ST","NCC-A.ST","NCC-B.ST","NDA-SE.ST","NENT-A.ST","NENT-B.ST","NET-B.ST","NIBE-B.ST","NOBI.ST","NOLA-B.ST","NYF.ST","PEAB-B.ST","PNDX-B.ST","RATO-A.ST","RATO-B.ST","RESURS.ST","SAAB-B.ST","SAGA-A.ST","SAGA-B.ST","SAGA-D.ST","SAGA-PREF.ST","SAND.ST","SBB-B.ST","SBB-D.ST","SCA-A.ST","SCA-B.ST","SEB-A.ST","SEB-C.ST","SECU-B.ST","SHB-A.ST","SHB-B.ST","SKA-B.ST","SKF-A.ST","SKF-B.ST","SOBI.ST","SSAB-A.ST","SSAB-B.ST","STE-A.ST","STE-R.ST","SWEC-A.ST","SWEC-B.ST","SWED-A.ST","SWMA.ST","TEL2-A.ST","TEL2-B.ST","TELIA.ST","THULE.ST","TIETOS.ST","TIGO-SDB.ST","TREL-B.ST","VITR.ST","VNE-SDB.ST","VOLV-A.ST","VOLV-B.ST","WALL-B.ST","WIHL.ST","ACAD.ST","ADAPT.ST","ALIF-B.ST","ALIG.ST","AMBEA.ST","ANOD-B.ST","AOI.ST","AQ.ST","ATORX.ST","BEIA-B.ST","BERG-B.ST","BESQ.ST","BETCO.ST","BHG.ST","BILI-A.ST","BIOA-B.ST","BIOG-B.ST","BIOT.ST","BMAX.ST","BOOZT.ST","BTS-B.ST","BUFAB.ST","BULTEN.ST","BURE.ST","CALTX.ST","CAMX.ST","CAT-A.ST","CAT-B.ST")

companies_usa = c("FB", "GOLD", "MMM","AOS","ABT","ABBV","ACN","ATVI","AYI","ADBE","AAP","AMD","AES","AET","AMG","AFL","A","APD","AKAM","ALK","ALB","ARE","ALXN","ALGN","ALLE","AGN","ADS","LNT","ALL","GOOGL","GOOG","MO","AMZN","AEE","AAL","AEP","AXP","AIG","AMT","AWK","AMP","ABC","AME","AMGN","APH","APC","ADI","ANDV","ANSS","ANTM","AON","APA","AIV","AAPL","AMAT","APTV","ADM","ARNC","AJG","AIZ","T","ADSK","ADP","AZO","AVB","AVY","BHGE","BLL","BAC","BAX","BBT","BDX","BRK.B","BBY","BIIB","BLK","HRB","BA","BKNG","BWA","BXP","BSX","BHF","BMY","AVGO","BF.B","CHRW","CA","COG","CDNS","CPB","COF","CAH","KMX","CCL","CAT","CBOE","CBRE","CBS","CELG","CNC","CNP","CTL","CERN","CF","SCHW","CHTR","CVX","CMG","CB","CHD","CI","XEC","CINF","CTAS","CSCO","C","CFG","CTXS","CME","CMS","KO","CTSH","CL","CMCSA","CMA","CAG","CXO","COP","ED","STZ","GLW","COST","COTY","CCI","CSRA","CSX","CMI","CVS","DHI","DHR","DRI","DVA","DE","DAL","XRAY","DVN","DLR","DFS","DISCA","DISCK","DISH","DG","DLTR","D","DOV","DWDP","DPS","DTE","DUK","DRE","DXC","ETFC","EMN","ETN","EBAY","ECL","EIX","EW","EA","EMR","ETR","EVHC","EOG","EQT","EFX","EQIX","EQR","ESS","EL","RE","ES","EXC","EXPE","EXPD","ESRX","EXR","XOM","FFIV","FB","FAST","FRT","FDX","FIS","FITB","FE","FISV","FLIR","FLS","FLR","FMC","FL","F","FTV","FBHS","BEN","FCX","GPS","GRMN","IT","GD","GE","GGP","GIS","GM","GPC","GILD","GPN","GS","GT","GWW","HAL","HBI","HOG","HRS","HIG","HAS","HCA","HCP","HP","HSIC","HES","HPE","HLT","HOLX","HD","HON","HRL","HST","HPQ","HUM","HBAN","HII","IDXX","INFO","ITW","ILMN","INCY","IR","INTC","ICE","IBM","IP","IPG","IFF","INTU","ISRG","IVZ","IPGP","IQV","IRM","JBHT","JEC","SJM","JNJ","JCI","JPM","JNPR","KSU","K","KEY","KMB","KIM","KMI","KLAC","KSS","KHC","KR","LB","LLL","LH","LRCX","LEG","LEN","LUK","LLY","LNC","LKQ","LMT","L","LOW","LYB","MTB","MAC","M","MRO","MPC","MAR","MMC","MLM","MAS","MA","MAT","MKC","MCD","MCK","MDT","MRK","MET","MTD","MGM","KORS","MCHP","MU","MSFT","MAA","MHK","TAP","MDLZ","MON","MNST","MCO","MS","MSI","MYL","NDAQ","NOV","NAVI","NKTR","NTAP","NFLX","NWL","NFX","NEM","NWSA","NWS","NEE","NLSN","NKE","NI","NBL","JWN","NSC","NTRS","NOC","NCLH","NRG","NUE","NVDA","ORLY","OXY","OMC","OKE","ORCL","PCAR","PKG","PH","PAYX","PYPL","PNR","PBCT","PEP","PKI","PRGO","PFE","PCG","PM","PSX","PNW","PXD","PNC","RL","PPG","PPL","PX","PFG","PG","PGR","PLD","PRU","PEG","PSA","PHM","PVH","QRVO","QCOM","PWR","DGX","RRC","RJF","RTN","O","RHT","REG","REGN","RF","RSG","RMD","RHI","ROK","COL","ROP","ROST","RCL","SPGI","CRM","SBAC","SCG","SLB","STX","SEE","SRE","SHW","SPG","SWKS","SLG","SNA","SO","LUV","SWK","SBUX","STT","SRCL","SYK","STI","SIVB","SYMC","SYF","SNPS","SYY","TROW","TTWO","TPR","TGT","TEL","FTI","TXN","TXT","BK","CLX","COO","HSY","MOS","TRV","DIS","TMO","TIF","TWX","TJX","TMK","TSS","TSCO","TDG","TRIP","FOXA","FOX","TSN","USB","UDR","ULTA","UAA","UA","UNP","UAL","UNH","UPS","URI","UTX","UHS","UNM","VFC","VLO","VAR","VTR","VRSN","VRSK","VZ","VRTX","VIAB","V","VNO","VMC","WMT","WBA","WM","WAT","WEC","WFC","WELL","WDC","WU","WRK","WY","WHR","WMB","WLTW","WYN","WYNN","XEL","XRX","XLNX","XL","XYL","YUM","ZBH","ZION","ZTS")

#companies_usa = c("AAPL","MSFT","GOOGL","AMZN","FB","BRK-B","JPM","V","JNJ","WMT","BAC","PG","MA","XOM","T","UNH","INTC","DIS","VZ","HD","KO","MRK","WFC","CVX","PFE","CMCSA","CSCO","PEP","BA","C","ORCL","ADBE","NKE","ABT","MDT","BMY","MCD","CRM","NVDA","AMGN","NFLX","ACN","PM","ABBV","TMO","COST","UTX","PYPL","HON","LLY","AVGO","UNP","TXN","IBM","NEE","LIN","DHR","LMT","CHTR","SBUX","AXP","AMT","MMM","QCOM","UPS","GE","CVS","MO","USB","LOW","BKNG","FIS","MS","GILD","GS","CAT","MDLZ","FISV","SYK","BLK","ANTM","CI","TFC","EL","ADP","BDX","TJX","CME","COP","CB","PNC","ISRG","INTU","D","TMUS","SO","SPGI","DUK","TGT","ZTS")
#companies_usa = c("AACG","AAL","AAME","AAOI","AAON","AAPL","AAWW","AAXJ","AAXN","ABCB","ABEO","ABIO","ABMD","ABTX","ABUS","ACAD","ACAM","ACAMU","ACAMW","ACBI","ACER","ACGL","ACGLO","ACGLP","ACHC","ACHV","ACIA","ACIU","ACIW","ACLS","ACMR","ACNB","ACOR","ACRS","ACRX","ACST","ACT","ACTG","ACTT","ACTTU","ACTTW","ACWI","ACWX","ADAP","ADBE","ADES","ADI","ADIL","ADILW","ADMA","ADMP","ADMS","ADP","ADPT","ADRE","ADRO","ADSK","ADTN","ADUS","ADVM","ADXN","ADXS","AEGN","AEHR","AEIS","AEMD","AERI","AESE","AEY","AEYE","AEZS","AFH","AFIN","AFINP","AFMD","AFYA","AGBA","AGBAR","AGBAU","AGBAW","AGEN","AGFS","AGFSW","AGIO","AGLE","AGMH","AGNC","AGNCM","AGNCN","AGNCO","AGNCP","AGND","AGRX","AGTC","AGYS","AGZD","AHCO","AHPI","AIA","AIH","AIHS","AIKI","AIMC","AIMT","AINV","AIQ","AIRG","AIRR","AIRT","AIRTP","AIRTW","AKAM","AKBA","AKCA","AKER","AKRO","AKRX","AKTS","AKTX","ALAC","ALACR","ALACU","ALACW","ALBO","ALCO","ALDX","ALEC","ALGN","ALGR","ALGRR","ALGRU","ALGRW","ALGT","ALIM","ALJJ","ALKS","ALLK","ALLO","ALLT","ALNA","ALNY","ALOT","ALPN","ALRM","ALRN","ALRS","ALSK","ALT","ALTM","ALTR","ALTY","ALXN","ALYA","AMAG","AMAL","AMAT","AMBA","AMCA","AMCI","AMCIU","AMCIW","AMCX","AMD","AMED","AMEH","AMGN","AMHC","AMHCU","AMHCW","AMKR","AMNB","AMOT","AMPH","AMRB","AMRH","AMRHW","AMRK","AMRN","AMRS","AMSC","AMSF","AMSWA","AMTB","AMTBB","AMTD","AMTX","AMWD","AMZN","ANAB","ANAT","ANCN","ANDA","ANDAR","ANDAU","ANDAW","ANDE","ANGI","ANGL","ANGO","ANIK","ANIP","ANIX","ANPC","ANSS","ANTE","ANY","AOBC","AOSL","APDN","APEI","APEN","APEX","APLS","APLT","APM","APOG","APOP","APOPW","APPF","APPN","APPS","APRE","APTO","APTX","APVO","APWC","APXT","APXTU","APXTW","APYX","AQB","AQMS","AQST","ARAV","ARAY","ARCB","ARCC","ARCE","ARCT","ARDS","ARDX","AREC","ARGX","ARKR","ARLP","ARNA","AROW","ARPO","ARQT","ARTL","ARTLW","ARTNA","ARTW","ARVN","ARWR","ARYA","ARYAU","ARYAW","ASET","ASFI","ASLN","ASMB","ASML","ASNA","ASND","ASPS","ASPU","ASRT","ASRV","ASRVP","ASTC","ASTE","ASUR","ASYS","ATAX","ATCX","ATCXW","ATEC","ATEX","ATHE","ATHX","ATIF","ATLC","ATLO","ATNI","ATNX","ATOM","ATOS","ATRA","ATRC","ATRI","ATRO","ATRS","ATSG","ATVI","ATXI","AUB","AUBN","AUDC","AUPH","AUTL","AUTO","AVAV","AVCO","AVDL","AVEO","AVGO","AVGOP","AVGR","AVID","AVNW","AVRO","AVT","AVXL","AWRE","AXAS","AXDX","AXGN","AXGT","AXLA","AXNX","AXSM","AXTI","AY","AYTU","AZPN","AZRX","BAND","BANF","BANFP","BANR","BANX","BASI","BATRA","BATRK","BBBY","BBCP","BBGI","BBH","BBI","BBIO","BBQ","BBSI","BCBP","BCDA","BCDAW","BCEL","BCLI","BCML","BCOM","BCOR","BCOV","BCOW","BCPC","BCRX","BCTF","BCYC","BDGE","BDSI","BDTX","BEAM","BEAT","BECN","BELFA","BELFB","BFC","BFIN","BFIT","BFRA","BFST","BFYT","BGCP","BGFV","BGNE","BGRN","BHAT","BHF","BHFAL","BHFAP","BHTG","BIB","BICK","BIDU","BIIB","BILI","BIMI","BIOC","BIOL","BIS","BJK","BJRI","BKCC","BKEP","BKEPP","BKNG","BKSC","BKYI","BL","BLBD","BLCM","BLCN","BLDP","BLDR","BLFS","BLIN","BLKB","BLMN","BLNK","BLNKW","BLPH","BLRX","BLU","BLUE","BMCH","BMLP","BMRA","BMRC","BMRN","BMTC","BND","BNDW","BNDX","BNFT","BNGO","BNGOW","BNSO","BNTC","BNTCW","BNTX","BOCH","BOKF",
#                  "BOKFL","BOMN","BOOM","BOSC","BOTJ","BOTZ","BOXL","BPFH","BPMC","BPOP","BPOPM","BPOPN","BPRN","BPTH","BPY","BPYPN","BPYPO","BPYPP","BPYU","BPYUP","BREW","BRID","BRKL","BRKR","BRKS","BROG","BROGW","BRP","BRPA","BRPAR","BRPAU","BRPAW","BRQS","BRY","BSAE","BSBE","BSBK","BSCE","BSCK","BSCL","BSCM","BSCN","BSCO","BSCP","BSCQ","BSCR","BSCS","BSCT","BSDE","BSET","BSGM","BSJK","BSJL","BSJM","BSJN","BSJO","BSJP","BSJQ","BSJR","BSML","BSMM","BSMN","BSMO","BSMP","BSMQ","BSMR","BSMS","BSMT","BSQR","BSRR","BSTC","BSVN","BTAI","BTEC","BUG","BURG","BUSE","BVSN","BVXV","BVXVW","BWAY","BWB","BWEN","BWFG","BWMX","BXRX","BYFC","BYND","BYSI","BZUN","CAAS","CABA","CAC","CACC","CACG","CAKE","CALA","CALB","CALM","CAMP","CAMT","CAN","CAPR","CAR","CARA","CARE","CARG","CARO","CARV","CARZ","CASA","CASH","CASI","CASS","CASY","CATB","CATC","CATH","CATM","CATS","CATY","CBAN","CBAT","CBAY","CBFV","CBIO","CBLI","CBMB","CBMG","CBNK","CBPO","CBRL","CBSH","CBSHP","CBTX","CCAP","CCB","CCBG","CCCL","CCD","CCLP","CCMP","CCNE","CCOI","CCRC","CCRN","CCXI","CDC","CDEV","CDK","CDL","CDLX","CDMO","CDMOP","CDNA","CDNS","CDTX","CDW","CDXC","CDXS","CDZI","CECE","CELC","CELH","CEMI","CENT","CENTA","CENX","CERC","CERN","CERS","CETV","CETX","CETXP","CETXW","CEVA","CEY","CEZ","CFA","CFB","CFBI","CFBK","CFFA","CFFAU","CFFAW","CFFI","CFFN","CFMS","CFO","CFRX","CG","CGBD","CGEN","CGIX","CGNX","CGO","CHCI","CHCO","CHDN","CHEF","CHEK","CHEKZ","CHFS","CHI","CHKP","CHMA","CHMG","CHNA","CHNG","CHNGU","CHNGV","CHNR","CHPM","CHPMU","CHPMW","CHRS","CHRW","CHSCL","CHSCM","CHSCN","CHSCO","CHSCP","CHTR","CHUY","CHW","CHY","CIBR","CID","CIDM","CIFS","CIGI","CIH","CIIC","CIICU","CIICW","CIL","CINF","CIVB","CIZ","CIZN","CJJD","CKPT","CLAR","CLBK","CLBS","CLCT","CLDB","CLDX","CLFD","CLGN","CLIR","CLLS","CLMT","CLNE","CLOU","CLPS","CLPT","CLRB","CLRBZ","CLRG","CLRO","CLSD","CLSK","CLSN","CLUB","CLVS","CLWT","CLXT","CMBM","CMCO","CMCSA","CMCT","CMCTP","CME","CMFNL","CMLS","CMPR","CMRX","CMTL","CNAT","CNBKA","CNCE","CNCR","CNDT","CNET","CNFR","CNFRL","CNNB","CNOB","CNSL","CNSP","CNST","CNTG","CNTY","CNXN","COCP","CODA","CODX","COFS","COHR","COHU","COKE","COLB","COLL","COLM","COMM","COMT","CONE","CONN","COOP","CORE","CORT","CORV","COST","COUP","COWN","COWNL","COWNZ","CPAA","CPAAU","CPAAW","CPAH","CPHC","CPIX","CPLP","CPRT","CPRX","CPSH","CPSI","CPSS","CPST","CPTA","CPTAG","CPTAL","CPZ","CRAI","CRBP","CREE","CREG","CRESY","CREX","CREXW","CRIS","CRMT","CRNC","CRNT","CRNX","CRON","CROX","CRSA","CRSAU","CRSAW","CRSP","CRTO","CRTX","CRUS","CRVL","CRVS","CRWD","CRWS","CSA","CSB","CSBR","CSCO","CSF","CSFL","CSGP","CSGS","CSII","CSIQ","CSML","CSOD","CSPI","CSQ","CSSE","CSSEP","CSTE","CSTL","CSTR","CSWC","CSWCL","CSWI","CSX","CTAC","CTACU","CTACW","CTAS","CTBI","CTG","CTHR","CTIB","CTIC","CTMX","CTRC","CTRE","CTRM","CTRN","CTSH","CTSO","CTXR","CTXRW","CTXS","CUBA","CUE","CUI","CUTR","CVBF","CVCO","CVCY","CVET","CVGI","CVGW","CVLT","CVLY","CVTI","CVV","CWBC","CWBR","CWCO","CWST","CXDC","CXSE","CY","CYAD","CYAN","CYBE","CYBR","CYCC","CYCCP","CYCN","CYOU","CYRN","CYRX","CYRXW","CYTK","CZNC","CZR","CZWI","DAIO","DAKT","DALI",
#                  "DARE","DAX","DBVT","DBX","DCAR","DCIX","DCOM","DCOMP","DCPH","DDIV","DDMX","DDMXW","DDOG","DEAC","DEACU","DEACW","DENN","DFFN","DFNL","DFNSU","DFPHU","DGICA","DGICB","DGII","DGLD","DGLY","DGRE","DGRS","DGRW","DHC","DHCNI","DHCNL","DHIL","DINT","DIOD","DISCA","DISCB","DISCK","DISH","DJCO","DLHC","DLPN","DLPNW","DLTH","DLTR","DMAC","DMLP","DMPI","DMRC","DMTK","DNJR","DNKN","DNLI","DOCU","DOGZ","DOMO","DOOO","DORM","DOX","DOYU","DPHC","DPHCU","DPHCW","DRAD","DRADP","DRIO","DRIOW","DRIV","DRNA","DRRX","DRTT","DSGX","DSKE","DSKEW","DSLV","DSPG","DSWL","DTEA","DTIL","DTSS","DUO","DUOT","DUSA","DVAX","DVLU","DVOL","DVY","DWAS","DWAT","DWAW","DWCR","DWEQ","DWFI","DWLD","DWMC","DWPP","DWSH","DWSN","DWUS","DXCM","DXGE","DXJS","DXLG","DXPE","DXYN","DYAI","DYNT","DZSI","EA","EARS","EAST","EBAY","EBAYL","EBIX","EBIZ","EBMT","EBSB","EBTC","ECHO","ECOL","ECOLW","ECOR","ECOW","ECPG","EDAP","EDIT","EDNT","EDRY","EDSA","EDTX","EDTXU","EDTXW","EDUC","EEFT","EEMA","EFAS","EFOI","EFSC","EGAN","EGBN","EGLE","EGOV","EGRX","EH","EHTH","EIDX","EIGI","EIGR","EKSO","ELGX","ELOX","ELSE","ELTK","EMB","EMCB","EMCF","EMCG","EMIF","EMKR","EML","EMMS","EMXC","ENDP","ENG","ENLV","ENOB","ENPH","ENSG","ENT","ENTA","ENTG","ENTX","ENTXW","ENZL","EOLS","EPAY","EPIX","EPSN","EPZM","EQ","EQBK","EQIX","EQRR","ERI","ERIC","ERIE","ERII","ERYP","ESBK","ESCA","ESEA","ESGD","ESGE","ESGR","ESGRO","ESGRP","ESGU","ESLT","ESPO","ESPR","ESQ","ESSA","ESSC","ESSCU","ESTA","ESXB","ETFC","ETNB","ETON","ETSY","ETTX","EUFN","EVBG","EVER","EVFM","EVGN","EVK","EVLO","EVOK","EVOL","EVOP","EVSI","EVSIW","EWBC","EWJE","EWJV","EWZS","EXAS","EXC","EXEL","EXFO","EXLS","EXPC","EXPCU","EXPCW","EXPD","EXPE","EXPI","EXPO","EXTR","EYE","EYEG","EYEGW","EYEN","EYES","EYESW","EYPT","EZPW","FAAR","FAB","FAD","FALN","FAMI","FANG","FANH","FARM","FARO","FAST","FAT","FATE","FB","FBIO","FBIOP","FBIZ","FBMS","FBNC","FBSS","FBZ","FCA","FCAL","FCAN","FCAP","FCBC","FCBP","FCCO","FCCY","FCEF","FCEL","FCFS","FCNCA","FCNCP","FCVT","FDBC","FDEF","FDIV","FDNI","FDT","FDTS","FDUS","FDUSG","FDUSL","FDUSZ","FEIM","FELE","FEM","FEMB","FEMS","FENC","FEP","FEUZ","FEX","FEYE","FFBC","FFBW","FFHL","FFIC","FFIN","FFIV","FFNW","FFWM","FGBI","FGEN","FGM","FHB","FHK","FIBK","FID","FINX","FISI","FISV","FITB","FITBI","FITBO","FITBP","FIVE","FIVN","FIXD","FIXX","FIZZ","FJP","FKO","FKU","FLDM","FLEX","FLGT","FLIC","FLIR","FLL","FLLC","FLLCR","FLLCU","FLLCW","FLMN","FLMNW","FLN","FLNT","FLWS","FLXN","FLXS","FMAO","FMB","FMBH","FMBI","FMCI","FMCIU","FMCIW","FMHI","FMK","FMNB","FNCB","FNHC","FNJN","FNK","FNKO","FNLC","FNWB","FNX","FNY","FOCS","FOLD","FOMX","FONR","FORD","FORK","FORM","FORR","FORTY","FOSL","FOX","FOXA","FOXF","FPA","FPAY","FPRX","FPXE","FPXI","FRAF","FRAN","FRBA","FRBK","FREQ","FRG","FRGI","FRHC","FRME","FRPH","FRPT","FRSX","FRTA","FSBC","FSBW","FSCT","FSEA","FSFG","FSLR","FSRV","FSRVU","FSRVW","FSTR","FSV","FSZ","FTA","FTAC","FTACU","FTACW","FTAG","FTC","FTCS","FTDR","FTEK","FTFT","FTGC","FTHI","FTLB","FTNT","FTR","FTRI","FTSL","FTSM","FTSV","FTXD","FTXG","FTXH","FTXL","FTXN","FTXO","FTXR","FULC","FULT","FUNC","FUND","FUSB","FUTU",
#                  "FUV","FV","FVC","FVCB","FVE","FWONA","FWONK","FWP","FWRD","FXNC","FYC","FYT","FYX","GABC","GAIA","GAIN","GAINL","GAINM","GALT","GARS","GASS","GBCI","GBDC","GBLI","GBLIL","GBLIZ","GBT","GCBC","GCVRZ","GDEN","GDS","GDYN","GDYNW","GEC","GECC","GECCL","GECCM","GECCN","GENC","GENE","GENY","GEOS","GERN","GEVO","GFED","GFN","GFNCP","GFNSL","GGAL","GH","GHIVU","GHSI","GIFI","GIGE","GIGM","GIII","GILD","GILT","GLAD","GLADD","GLADL","GLBS","GLBZ","GLDD","GLDI","GLG","GLIBA","GLIBP","GLMD","GLNG","GLPG","GLPI","GLRE","GLUU","GLYC","GMAB","GMDA","GMHI","GMHIU","GMHIW","GMLP","GMLPP","GNCA","GNFT","GNLN","GNMA","GNMK","GNOM","GNPX","GNRSU","GNSS","GNTX","GNTY","GNUS","GO","GOGL","GOGO","GOOD","GOODM","GOODN","GOOG","GOOGL","GOSS","GPAQ","GPAQW","GPOR","GPP","GPRE","GPRO","GRBK","GRFS","GRID","GRIF","GRIL","GRIN","GRMN","GRNQ","GRNV","GRNVR","GRNVU","GRNVW","GROW","GRPN","GRTS","GRTX","GRVY","GRWG","GSBC","GSHD","GSIT","GSKY","GSM","GSMG","GSMGW","GSUM","GT","GTEC","GTHX","GTIM","GTLS","GTYH","GULF","GURE","GVP","GWGH","GWPH","GWRS","GXGX","GXGXU","GXGXW","GXTG","GYRO","HA","HABT","HAFC","HAIN","HALL","HALO","HAPP","HARP","HAS","HAYN","HBAN","HBANN","HBANO","HBCP","HBIO","HBMD","HBNC","HBP","HBT","HCAC","HCACU","HCACW","HCAP","HCAPZ","HCAT","HCCH","HCCHR","HCCHW","HCCI","HCCO","HCCOU","HCCOW","HCKT","HCM","HCSG","HDS","HDSN","HEAR","HEBT","HEES","HELE","HEPA","HERD","HERO","HEWG","HFBL","HFFG","HFWA","HGSH","HHHH","HHHHR","HHHHU","HHHHW","HHR","HHT","HIBB","HIFS","HIHO","HIIQ","HIMX","HJLI","HJLIW","HLAL","HLG","HLIO","HLIT","HLNE","HMHC","HMNF","HMST","HMSY","HMTV","HNDL","HNNA","HNRG","HOFT","HOLI","HOLX","HOMB","HONE","HOOK","HOPE","HOTH","HOVNP","HQI","HQY","HROW","HRTX","HRZN","HSDT","HSIC","HSII","HSKA","HSON","HSTM","HTBI","HTBK","HTBX","HTGM","HTHT","HTIA","HTLD","HTLF","HUBG","HUGE","HUIZ","HURC","HURN","HVBC","HWBK","HWC","HWCC","HWCPL","HWKN","HX","HYAC","HYACU","HYACW","HYLS","HYND","HYRE","HYXE","HYZD","HZNP","IAC","IART","IBB","IBCP","IBKC","IBKCN","IBKCO","IBKCP","IBKR","IBOC","IBTA","IBTB","IBTD","IBTE","IBTF","IBTG","IBTH","IBTI","IBTJ","IBTX","IBUY","ICAD","ICBK","ICCC","ICCH","ICFI","ICHR","ICLK","ICLN","ICLR","ICMB","ICON","ICPT","ICUI","IDCC","IDEX","IDLB","IDN","IDRA","IDXG","IDXX","IDYA","IEA","IEAWW","IEC","IEF","IEI","IEP","IESC","IEUS","IFEU","IFGL","IFMK","IFRX","IFV","IGF","IGIB","IGIC","IGICW","IGMS","IGOV","IGSB","IHRT","III","IIIN","IIIV","IIN","IIVI","IJT","IKNX","ILMN","ILPT","IMAB","IMAC","IMACW","IMBI","IMGN","IMKTA","IMMP","IMMR","IMMU","IMOS","IMRA","IMRN","IMRNW","IMTE","IMUX","IMV","IMVT","IMVTU","IMVTW","IMXI","INAP","INBK","INBKL","INBKZ","INCY","INDB","INDY","INFI","INFN","INFR","INGN","INMB","INMD","INNT","INO","INOD","INOV","INPX","INSE","INSG","INSM","INSU","INSUU","INSUW","INTC","INTG","INTL","INTU","INVA","INVE","INWK","IONS","IOSP","IOTS","IOVA","IPAR","IPGP","IPHA","IPKW","IPLDP","IPWR","IQ","IRBT","IRCP","IRDM","IRIX","IRMD","IROQ","IRTC","IRWD","ISBC","ISDS","ISDX","ISEE","ISEM","ISHG","ISIG","ISNS","ISRG","ISSC","ISTB","ISTR","ITCI","ITI","ITIC","ITMR","ITRI","ITRM","ITRN","IUS","IUSB","IUSG","IUSS","IUSV",
#                  "IVAC","IXUS","IZEA","JACK","JAGX","JAKK","JAN","JAZZ","JBHT","JBLU","JBSS","JCOM","JCS","JCTCF","JD","JFIN","JFK","JFKKR","JFKKU","JFKKW","JFU","JG","JJSF","JKHY","JKI","JMPNL","JMPNZ","JNCE","JOBS","JOUT","JRJC","JRSH","JRVR","JSM","JSMD","JSML","JVA","JYNT","KALA","KALU","KALV","KBAL","KBLM","KBLMR","KBLMU","KBLMW","KBSF","KBWB","KBWD","KBWP","KBWR","KBWY","KCAPL","KE","KELYA","KELYB","KEQU","KERN","KERNW","KFFB","KFRC","KGJI","KHC","KIDS","KIN","KINS","KIRK","KLAC","KLDO","KLIC","KLXE","KMDA","KMPH","KNDI","KNSA","KNSL","KOD","KOPN","KOSS","KPTI","KRKR","KRMA","KRMD","KRNT","KRNY","KRTX","KRUS","KRYS","KTCC","KTOS","KTOV","KTOVW","KURA","KVHI","KXIN","KZIA","KZR","LACQ","LACQU","LACQW","LAKE","LAMR","LANC","LAND","LANDP","LARK","LASR","LATN","LATNU","LATNW","LAUR","LAWS","LAZY","LBAI","LBC","LBRDA","LBRDK","LBTYA","LBTYB","LBTYK","LCA","LCAHU","LCAHW","LCNB","LCUT","LDEM","LDSF","LE","LECO","LEDS","LEGH","LEGR","LEVL","LFAC","LFACU","LFACW","LFUS","LFVN","LGIH","LGND","LHCG","LIFE","LILA","LILAK","LINC","LIND","LIQT","LITE","LIVE","LIVK","LIVKU","LIVKW","LIVN","LIVX","LIZI","LJPC","LK","LKCO","LKFN","LKQ","LLIT","LLNW","LMAT","LMB","LMBS","LMFA","LMFAW","LMNL","LMNR","LMNX","LMPX","LMRK","LMRKN","LMRKO","LMRKP","LMST","LNDC","LNGR","LNT","LNTH","LOAC","LOACR","LOACU","LOACW","LOAN","LOB","LOCO","LOGC","LOGI","LOGM","LONE","LOOP","LOPE","LORL","LOVE","LPCN","LPLA","LPSN","LPTH","LPTX","LQDA","LQDT","LRCX","LRGE","LSACU","LSBK","LSCC","LSTR","LSXMA","LSXMB","LSXMK","LTBR","LTRPA","LTRPB","LTRX","LULU","LUMO","LUNA","LVGO","LVHD","LWAY","LX","LXRX","LYFT","LYL","LYTS","MACK","MAGS","MANH","MANT","MAR","MARA","MARK","MARPS","MASI","MAT","MATW","MAYS","MBB","MBCN","MBII","MBIN","MBINO","MBINP","MBIO","MBNKP","MBOT","MBRX","MBSD","MBUU","MBWM","MCBC","MCBS","MCEF","MCEP","MCFT","MCHI","MCHP","MCHX","MCMJ","MCMJW","MCRB","MCRI","MDB","MDCA","MDGL","MDGS","MDGSW","MDIA","MDIV","MDJH","MDLZ","MDRR","MDRRP","MDRX","MDWD","MEDP","MEDS","MEET","MEIP","MELI","MEOH","MERC","MESA","MESO","METC","MFH","MFIN","MFINL","MFNC","MFSF","MGEE","MGEN","MGI","MGIC","MGLN","MGNX","MGPI","MGRC","MGTA","MGTX","MGYR","MHLD","MICT","MIDD","MIK","MILN","MIME","MIND","MINDP","MINI","MIRM","MIST","MITK","MITO","MJCO","MKD","MKGI","MKSI","MKTX","MLAB","MLCO","MLHR","MLND","MLNX","MLVF","MMAC","MMLP","MMSI","MMYT","MNCL","MNCLU","MNCLW","MNDO","MNKD","MNLO","MNOV","MNPR","MNRO","MNSB","MNST","MNTA","MNTX","MOBL","MOFG","MOGO","MOHO","MOMO","MOR","MORF","MORN","MOSY","MOTS","MOXC","MPAA","MPB","MPWR","MRAM","MRBK","MRCC","MRCCL","MRCY","MREO","MRIN","MRKR","MRLN","MRNA","MRNS","MRSN","MRTN","MRTX","MRUS","MRVL","MSBF","MSBI","MSEX","MSFT","MSON","MSTR","MSVB","MTBC","MTBCP","MTC","MTCH","MTEM","MTEX","MTLS","MTP","MTRX","MTSC","MTSI","MTSL","MU","MUDS","MUDSU","MUDSW","MVBF","MVIS","MWK","MXIM","MYFW","MYGN","MYL","MYOK","MYOS","MYRG","MYSZ","MYT","NAII","NAKD","NAOV","NATH","NATI","NATR","NAVI","NBACU","NBEV","NBIX","NBL","NBLX","NBN","NBRV","NBSE","NBTB","NCBS","NCMI","NCNA","NCSM","NCTY","NDAQ","NDLS","NDRA","NDRAW","NDSN","NEBU","NEBUU","NEBUW","NEO","NEOG","NEON","NEOS",
#                  "NEPH","NEPT","NERV","NESR","NESRW","NETE","NEWA","NEWT","NEWTI","NEWTL","NEXT","NFBK","NFE","NFIN","NFINU","NFINW","NFLX","NFTY","NGHC","NGHCN","NGHCO","NGHCP","NGHCZ","NGM","NH","NHLD","NHLDW","NHTC","NICE","NICK","NIU","NK","NKSH","NKTR","NLNK","NLOK","NLTX","NMCI","NMIH","NMRD","NMRK","NNBR","NNDM","NODK","NOVN","NOVT","NPA","NPAUU","NPAWW","NRBO","NRC","NRIM","NSEC","NSIT","NSSC","NSTG","NSYS","NTAP","NTCT","NTEC","NTES","NTGN","NTGR","NTIC","NTLA","NTNX","NTRA","NTRP","NTRS","NTRSO","NTUS","NTWK","NUAN","NURO","NUROW","NUVA","NVAX","NVCN","NVCR","NVDA","NVEC","NVEE","NVFY","NVIV","NVMI","NVUS","NWBI","NWFL","NWGI","NWL","NWLI","NWPX","NWS","NWSA","NXGN","NXPI","NXST","NXTC","NXTD","NXTG","NYMT","NYMTM","NYMTN","NYMTO","NYMTP","NYMX","OAS","OBAS","OBCI","OBLN","OBNK","OBSV","OCC","OCCI","OCCIP","OCFC","OCGN","OCSI","OCSL","OCSLL","OCUL","ODFL","ODP","ODT","OESX","OFED","OFIX","OFLX","OFS","OFSSI","OFSSL","OFSSZ","OGI","OIIM","OKTA","OLD","OLED","OLLI","OMAB","OMCL","OMER","OMEX","OMP","ON","ONB","ONCS","ONCT","ONCY","ONEM","ONEQ","ONEW","ONTX","ONTXW","ONVO","OPB","OPBK","OPCH","OPES","OPESW","OPGN","OPGNW","OPHC","OPI","OPINI","OPK","OPNT","OPOF","OPRA","OPRT","OPRX","OPTN","OPTT","ORBC","ORG","ORGO","ORGS","ORLY","ORMP","ORRF","ORSN","ORSNR","ORSNU","ORSNW","ORTX","OSBC","OSIS","OSMT","OSN","OSPN","OSS","OSTK","OSUR","OSW","OTEL","OTEX","OTIC","OTLK","OTLKW","OTTR","OTTW","OVBC","OVID","OVLY","OXBR","OXBRW","OXFD","OXLC","OXLCM","OXLCO","OXLCP","OXSQ","OXSQL","OXSQZ","OYST","OZK","PAAC","PAACR","PAACU","PAACW","PAAS","PACB","PACQ","PACQU","PACQW","PACW","PAE","PAEWW","PAHC","PANL","PASG","PATI","PATK","PAVM","PAVMW","PAVMZ","PAYS","PAYX","PBBI","PBCT","PBCTP","PBFS","PBHC","PBIP","PBPB","PBTS","PBYI","PCAR","PCB","PCH","PCOM","PCRX","PCSB","PCTI","PCTY","PCYG","PCYO","PDBC","PDCE","PDCO","PDD","PDEV","PDEX","PDFS","PDLB","PDLI","PDP","PDSB","PEBK","PEBO","PECK","PEGA","PEGI","PEIX","PENN","PEP","PERI","PESI","PETQ","PETS","PETZ","PEY","PEZ","PFBC","PFBI","PFF","PFG","PFHD","PFI","PFIE","PFIN","PFIS","PFLT","PFM","PFMT","PFPT","PFSW","PGC","PGEN","PGJ","PGNX","PGNY","PHAS","PHAT","PHCF","PHIO","PHIOW","PHO","PHUN","PHUNW","PI","PICO","PID","PIE","PIH","PIHPP","PINC","PIO","PIRS","PIXY","PIZ","PKBK","PKOH","PKW","PLAB","PLAY","PLBC","PLC","PLCE","PLIN","PLL","PLMR","PLPC","PLSE","PLUG","PLUS","PLW","PLXP","PLXS","PLYA","PMBC","PMD","PME","PMOM","PNBK","PNFP","PNNT","PNNTG","PNQI","PNRG","PNTG","POAI","PODD","POLA","POOL","POPE","POTX","POWI","POWL","PPBI","PPC","PPD","PPH","PPHI","PPIH","PPSI","PRAA","PRAH","PRCP","PRDO","PRFT","PRFZ","PRGS","PRGX","PRIM","PRN","PRNB","PROF","PROV","PRPH","PRPL","PRPO","PRQR","PRSC","PRTA","PRTH","PRTK","PRTS","PRVB","PRVL","PS","PSC","PSCC","PSCD","PSCE","PSCF","PSCH","PSCI","PSCM","PSCT","PSCU","PSEC","PSET","PSL","PSM","PSMT","PSNL","PSTI","PSTV","PSTVZ","PT","PTAC","PTACU","PTACW","PTC","PTCT","PTE","PTEN","PTF","PTGX","PTH","PTI","PTLA","PTMN","PTNR","PTON","PTSI","PTVCA","PTVCB","PUB","PUI","PULM","PUYI","PVAC","PVAL","PVBC","PWFL","PWOD","PXI","PXLW","PXS","PY","PYPL","PYZ","PZZA","QABA","QADA","QADB",
#                  "QAT","QBAK","QCLN","QCOM","QCRH","QDEL","QFIN","QIWI","QK","QLYS","QMCO","QNST","QQEW","QQQ","QQQX","QQXT","QRHC","QRTEA","QRTEB","QRVO","QTEC","QTNT","QTRX","QTT","QUIK","QUMU","QURE","QYLD","RADA","RAIL","RAND","RAPT","RARE","RARX","RAVE","RAVN","RBB","RBBN","RBCAA","RBCN","RBKB","RBNC","RBZ","RCEL","RCII","RCKT","RCKY","RCM","RCMT","RCON","RDCM","RDFN","RDHL","RDI","RDIB","RDNT","RDUS","RDVT","RDVY","RDWR","REAL","RECN","REDU","REED","REFR","REG","REGI","REGN","REKR","RELL","RELV","REPH","REPL","RESN","RETA","RETO","REXN","REYN","RFAP","RFDI","RFEM","RFEU","RFIL","RGCO","RGEN","RGLD","RGLS","RGNX","RIBT","RICK","RIGL","RILY","RILYG","RILYH","RILYI","RILYM","RILYN","RILYO","RILYP","RILYZ","RING","RIOT","RIVE","RKDA","RLMD","RMBI","RMBL","RMBS","RMCF","RMNI","RMR","RMTI","RNDB","RNDM","RNDV","RNEM","RNET","RNLC","RNMC","RNSC","RNST","RNWK","ROAD","ROBT","ROCK","ROIC","ROKU","ROLL","ROSE","ROSEU","ROSEW","ROST","RP","RPAY","RPD","RRBI","RRGB","RRR","RSSS","RTH","RTIX","RTLR","RTRX","RTTR","RUBY","RUHN","RUN","RUSHA","RUSHB","RUTH","RVMD","RVNC","RVSB","RWLK","RYAAY","RYTM","SABR","SAEX","SAFM","SAFT","SAGE","SAIA","SAL","SALM","SAMA","SAMAU","SAMAW","SAMG","SANM","SANW","SAQN","SAQNU","SAQNW","SASR","SATS","SAVA","SBAC","SBBP","SBBX","SBCF","SBFG","SBGI","SBLK","SBLKZ","SBNY","SBPH","SBRA","SBSI","SBT","SBUX","SCHL","SCHN","SCKT","SCON","SCOR","SCPH","SCPL","SCSC","SCVL","SCWX","SCYX","SCZ","SDC","SDG","SDGR","SDVY","SEAC","SECO","SEDG","SEED","SEEL","SEIC","SELB","SELF","SENEA","SENEB","SES","SESN","SFBC","SFBS","SFET","SFIX","SFM","SFNC","SFST","SG","SGA","SGBX","SGC","SGEN","SGH","SGLB","SGLBW","SGMA","SGMO","SGMS","SGOC","SGRP","SGRY","SHBI","SHEN","SHIP","SHIPW","SHIPZ","SHLO","SHOO","SHSP","SHV","SHY","SIBN","SIC","SIEB","SIEN","SIFY","SIGA","SIGI","SILC","SILK","SIMO","SINA","SINO","SINT","SIRI","SITM","SITO","SIVB","SIVBP","SKOR","SKYS","SKYW","SKYY","SLAB","SLCT","SLDB","SLGG","SLGL","SLGN","SLIM","SLM","SLMBP","SLNO","SLP","SLQD","SLRC","SLRX","SLS","SLVO","SMBC","SMBK","SMCI","SMCP","SMED","SMH","SMIT","SMMC","SMMCU","SMMCW","SMMF","SMMT","SMPL","SMRT","SMSI","SMTC","SMTX","SNBR","SNCA","SNCR","SND","SNDE","SNDL","SNDX","SNES","SNFCA","SNGX","SNGXW","SNLN","SNOA","SNPS","SNSR","SNSS","SNUG","SNY","SOCL","SOHO","SOHOB","SOHON","SOHOO","SOHU","SOLO","SOLOW","SOLY","SONA","SONG","SONGW","SONM","SONO","SORL","SOXX","SP","SPAR","SPCB","SPEX","SPFI","SPHS","SPI","SPKE","SPKEP","SPLK","SPNE","SPNS","SPOK","SPPI","SPRO","SPRT","SPSC","SPT","SPTN","SPWH","SPWR","SQBG","SQLV","SQQQ","SRAC","SRACU","SRACW","SRAX","SRCE","SRCL","SRDX","SRET","SREV","SRNE","SRPT","SRRA","SRRK","SRTS","SRTSW","SSB","SSBI","SSKN","SSNC","SSNT","SSP","SSPK","SSPKU","SSPKW","SSRM","SSSS","SSTI","SSYS","STAA","STAF","STAY","STBA","STCN","STFC","STIM","STKL","STKS","STLD","STML","STMP","STND","STNE","STOK","STRA","STRL","STRM","STRO","STRS","STRT","STSA","STX","STXB","SUMR","SUNS","SUNW","SUPN","SURF","SUSB","SUSC","SUSL","SVBI","SVC","SVMK","SVRA","SVVC","SWAV","SWIR","SWKH","SWKS","SWTX","SXTC","SY","SYBT","SYBX","SYKE","SYNA","SYNC","SYNH","SYNL","SYPR","SYRS","TA","TACO",
#                  "TACOW","TACT","TAIT","TANH","TANNI","TANNL","TANNZ","TAOP","TARA","TAST","TATT","TAYD","TBBK","TBIO","TBK","TBLT","TBLTW","TBNK","TBPH","TC","TCBI","TCBIL","TCBIP","TCBK","TCCO","TCDA","TCF","TCFC","TCFCP","TCMD","TCOM","TCON","TCPC","TCRD","TCRR","TCX","TDAC","TDACW","TDIV","TEAM","TECD","TECH","TECTP","TEDU","TELA","TELL","TENB","TENX","TER","TERP","TESS","TEUM","TFFP","TFSL","TGA","TGEN","TGLS","TGTX","TH","THBR","THBRU","THBRW","THCA","THCAU","THCAW","THCB","THCBU","THCBW","THFF","THMO","THRM","THTX","THWWW","TIBR","TIBRW","TIGO","TIGR","TILE","TIPT","TITN","TIVO","TLC","TLF","TLGT","TLND","TLRY","TLSA","TLT","TMDI","TMDX","TMSR","TMUS","TNAV","TNDM","TNXP","TOCA","TOPS","TORC","TOTA","TOTAR","TOTAU","TOTAW","TOUR","TOWN","TPCO","TPIC","TPTX","TQQQ","TRCH","TREE","TRHC","TRIB","TRIL","TRIP","TRMB","TRMD","TRMK","TRMT","TRNS","TRNX","TROV","TROW","TRPX","TRS","TRST","TRUE","TRUP","TRVG","TRVI","TRVN","TSBK","TSC","TSCAP","TSCBP","TSCO","TSEM","TSG","TSLA","TSRI","TTD","TTEC","TTEK","TTGT","TTMI","TTNP","TTOO","TTPH","TTTN","TTWO","TUES","TUR","TURN","TUSA","TUSK","TVIX","TVTY","TW","TWIN","TWMC","TWNK","TWNKW","TWOU","TWST","TXG","TXMD","TXN","TXRH","TYHT","TYME","TZAC","TZACU","TZACW","TZOO","UAE","UAL","UBCP","UBFO","UBIO","UBOH","UBSI","UBX","UCBI","UCTT","UEIC","UEPS","UFCS","UFO","UFPI","UFPT","UG","UGLD","UHAL","UIHC","ULBI","ULH","ULTA","UMBF","UMPQ","UMRX","UNAM","UNB","UNIT","UNTY","UONE","UONEK","UPLD","UPWK","URBN","URGN","UROV","USAK","USAP","USAU","USCR","USEG","USIG","USIO","USLB","USLM","USLV","USMC","USOI","USWS","USWSW","UTHR","UTMD","UTSI","UVSP","UXIN","VALU","VALX","VBFC","VBIV","VBLT","VBTX","VC","VCEL","VCIT","VCLT","VCNX","VCSH","VCTR","VCYT","VECO","VEON","VERB","VERBW","VERI","VERO","VERU","VERY","VETS","VFF","VG","VGIT","VGLT","VGSH","VIAC","VIACA","VIAV","VICR","VIE","VIGI","VIIX","VIOT","VIR","VIRC","VIRT","VISL","VIVE","VIVO","VKTX","VKTXW","VLGEA","VLY","VLYPO","VLYPP","VMBS","VMD","VNDA","VNET","VNOM","VNQI","VOD","VONE","VONG","VONV","VOXX","VRA","VRAY","VRCA","VREX","VRIG","VRML","VRNA","VRNS","VRNT","VRRM","VRSK","VRSN","VRTS","VRTU","VRTX","VSAT","VSDA","VSEC","VSMV","VSTM","VTC","VTGN","VTHR","VTIP","VTIQ","VTIQU","VTIQW","VTNR","VTSI","VTVT","VTWG","VTWO","VTWV","VUZI","VVPR","VVUS","VWOB","VXRT","VXUS","VYGR","VYMI","WABC","WAFD","WAFU","WASH","WATT","WB","WBA","WBND","WCLD","WDAY","WDC","WDFC","WEBK","WEN","WERN","WETF","WEYS","WHF","WHFBZ","WHLM","WHLR","WHLRD","WHLRP","WIFI","WILC","WINA","WINC","WING","WINS","WIRE","WISA","WIX","WKEY","WKHS","WLDN","WLFC","WLTW","WMGI","WNEB","WOOD","WORX","WPRT","WRLD","WRLS","WRLSR","WRLSW","WRTC","WSBC","WSBF","WSC","WSFS","WSG","WSTG","WSTL","WTBA","WTER","WTFC","WTFCM","WTRE","WTREP","WTRH","WVE","WVFC","WVVI","WVVIP","WW","WWD","WWR","WYNN","XAIR","XBIO","XBIOW","XBIT","XCUR","XEL","XELA","XELB","XENE","XENT","XERS","XFOR","XGN","XLNX","XLRN","XNCR","XNET","XOG","XOMA","XONE","XP","XPEL","XPER","XRAY","XSPA","XT","XTLB","YGYI","YGYIP","YI","YIN","YJ","YLCO","YLDE","YMAB","YNDX","YORW","YRCW","YTEN","YTRA","YVR","YY","Z","ZAGG","ZBIO","ZBRA","ZCMD","ZEAL","ZEUS","ZFGN",
#                  "ZG","ZGNX","ZGYHU","ZION","ZIONL","ZIONN","ZIONO","ZIONP","ZIONW","ZIOP","ZIV","ZIXI","ZKIN","ZLAB","ZM","ZN","ZNGA","ZS","ZSAN","ZUMZ","ZVO","ZYNE","ZYXI"
#                  )

                  
companies_l <- c("III.L","3IN.L","FOUR.L","ABF.L","ASL.L","ADM.L","AGK.L","AAF.L","AJB.L","ATST.L","AAL.L","ANTO.L","APAX.L","ASCL.L","ASHM.L","AHT.L","AGR.L","AML.L","AZN.L","AUTO.L","AVST.L","AVV.L","AGT.L","AV..L","BME.L","BAB.L","BA..L","BGFD.L","BAKK.L","BBY.L","BGEO.L","BNKR.L","BARC.L","BAG.L","BDEV.L","BBA.L","BBGI.L","BCA.L","BEZ.L","BWY.L","BKG.L","BHP.L","BYG.L","BRSC.L","BCPT.L","BGSC.L","BOY.L","BVS.L","BP..L","BRW.L","BATS.L","BLND.L","BVIC.L","BT.A.L","BNZL.L","BRBY.L","CNE.L","CLDN.L","CPI.L","CAPC.L","CARD.L","CCL.L","CEY.L","CNA.L","CINE.L","CTY.L","CKN.L","CBG.L","CLI.L","COA.L","COB.L","CCH.L","CPG.L","CCC.L","GLO.L","CTEC.L","CSP.L","CWK.L","CRST.L","CRH.L","CRDA.L","CYBG.L","DJAN.L","DCC.L","DPH.L","DLN.L","DGE.L","DPLM.L","DLG.L","DC..L","DOM.L","DRX.L","DNLM.L","EZJ.L","EDIN.L","EIG.L","ECM.L","ELM.L","ENOG.L","ETO.L","EQN.L","ESNT.L","ERM.L","EVR.L","EXPN.L","FCIT.L","FDM.L","FERG.L","FXPO.L","FSV.L","FCSS.L","FEV.L","FIN.L","FGT.L","FGP.L","FLTR.L","FSFL.L","FRES.L","FUTR.L","GFS.L","GFRD.L","GAW.L","GCP.L","DIGS.L","GSS.L","GNS.L","GSK.L","GLEN.L","GOG.L","GFTU.L","GRI.L","GPOR.L","UKW.L","GNC.L","GNK.L","GRG.L","GVC.L","HLMA.L","HMSO.L","HVPE.L","HL..L","HSTG.L","HAS.L","HSL.L","HRI.L","HGT.L","HICL.L","HIK.L","HILS.L","HFG.L","HSX.L","HOC.L","HSV.L","HWDN.L","HSBA.L","HTG.L","IBST.L","IGG.L","IMI.L","IMB.L","INCH.L","INF.L","ISAT.L","IHP.L","IHG.L","ICP.L","IAG.L","INPP.L","ITRK.L","INVP.L","IPO.L","ITV.L","IWG.L","FSJ.L","JD..L","JLG.L","JMAT.L","JAM.L","JMG.L","JII.L","JFJ.L","JEO.L","JUP.L","JE..L","KNOS.L","KAZ.L","KGF.L","LRE.L","LAND.L","LWDB.L","LGEN.L","LLOY.L","LSE.L","LMP.L","MNG.L","EMG.L","MKS.L","MSLH.L","MARS.L","MCS.L","MDC.L","MGGT.L","MRO.L","MRC.L","MERL.L","MCRO.L","MAB.L","MNDI.L","MONY.L","MNKS.L","MGAM.L","MRW.L","MYI.L","NEX.L","NG..L","NBLS.L","NETW.L","NRR.L","NXT.L","NESF.L","NMC.L","OCDO.L","OSB.L","OXIG.L","PAGE.L","PIN.L","PAG.L","PAY.L","PSON.L","PNN.L","PLI.L","PSH.L","PSN.L","PNL.L","PFC.L","PETS.L","PHNX.L","PTEC.L","PLUS.L","PCT.L","POLY.L","PLP.L","PPH.L","PMO.L","PHP.L","PFG.L","PRU.L","PRTC.L","PZC.L","QQ..L","QLT.L","RNK.L","RAT.L","RB..L","RDW.L","REL.L","TRIG.L","RSW.L","RTO.L","RTN.L","RHIM.L","RMV.L","RIO.L","RCP.L","RSE.L","RR..L","ROR.L","RBS.L","RDSA.L","RDSB.L","RMG.L","RSA.L","SBRE.L","SAFE.L","SGE.L","SBRY.L","SNN.L","SVS.L","SDP.L","SOI.L","SDR.L","SCIN.L","SMT.L","SGRO.L","SNR.L","SEQI.L","SRP.L","SVT.L","SHB.L","SHI.L","SRE.L","SN..L","SMDS.L","SMIN.L","SSON.L","SKG.L","SCT.L","SOPH.L","SXS.L","SPX.L","SPT.L","SPD.L","SSE.L","SSPG.L","STJ.L","SMP.L","SGC.L","STAN.L","SLA.L","SYNC.L","SYNT.L","TALK.L","TATE.L","TW..L","TBCG.L","TEP.L","TMPL.L","TEM.L","TSCO.L","TIFS.L","TCAP.L","TRY.L","TRN.L","TPK.L","BBOX.L","TUI.L","TLW.L","UDG.L","UKCM.L","ULE.L","ULVR.L","UTG.L","UU..L","VSVS.L","VCT.L","VEIL.L","VOF.L","VVO.L","VOD.L","WOSG.L","WEIR.L","JDW.L","SMWH.L","WTB.L","WMH.L","WTAN.L","WIZZ.L","WG..L","WKP.L","WWH.L","WPP.L")
companies <- c(companies_usa)
               #, companies_l, test, test2)
#companies <- c(test, test2)
#companies <- c(companies_usa)
#companies <- companies_l
#companies <- c("MMM","AOS","ABT","ABBV","ACN","ATVI","AYI","ADBE","AAP","AMD","AES","AET","AMG","AFL","A","APD","AKAM","ALK","ALB","ARE","ALXN","ALGN","ALLE","AGN","ADS","LNT","ALL","GOOGL","GOOG","MO","AMZN","AEE","AAL","AEP","AXP","AIG","AMT","AWK","AMP","ABC","AME","AMGN","APH","APC","ADI","ANDV","ANSS","ANTM","AON","APA","AIV","AAPL","AMAT","APTV","ADM","ARNC","AJG","AIZ","T","ADSK","ADP","AZO","AVB","AVY","BHGE","BLL","BAC","BAX","BBT","BDX","BRK.B","BBY","BIIB","BLK","HRB","BA","BKNG","BWA","BXP","BSX","BHF","BMY","AVGO","BF.B","CHRW","CA","COG","CDNS","CPB","COF","CAH","KMX","CCL","CAT","CBOE","CBRE","CBS","CELG","CNC","CNP","CTL","CERN","CF","SCHW","CHTR","CVX","CMG","CB","CHD","CI","XEC","CINF","CTAS","CSCO","C","CFG","CTXS","CME","CMS","KO","CTSH","CL","CMCSA","CMA","CAG","CXO","COP","ED","STZ","GLW","COST","COTY","CCI","CSRA","CSX","CMI","CVS","DHI","DHR","DRI","DVA","DE","DAL","XRAY","DVN","DLR","DFS","DISCA","DISCK","DISH","DG","DLTR","D","DOV","DWDP","DPS","DTE","DUK","DRE","DXC","ETFC","EMN","ETN","EBAY","ECL","EIX","EW","EA","EMR","ETR","EVHC","EOG","EQT","EFX","EQIX","EQR","ESS","EL","RE","ES","EXC","EXPE","EXPD","ESRX","EXR","XOM","FFIV","FB","FAST","FRT","FDX","FIS","FITB","FE","FISV","FLIR","FLS","FLR","FMC","FL","F","FTV","FBHS","BEN","FCX","GPS","GRMN","IT","GD","GE","GGP","GIS","GM","GPC","GILD","GPN","GS","GT","GWW","HAL","HBI","HOG","HRS","HIG","HAS","HCA","HCP","HP","HSIC","HES","HPE","HLT","HOLX","HD","HON","HRL","HST","HPQ","HUM","HBAN","HII","IDXX","INFO","ITW","ILMN","INCY","IR","INTC","ICE","IBM","IP","IPG","IFF","INTU","ISRG","IVZ","IPGP","IQV","IRM","JBHT","JEC","SJM","JNJ","JCI","JPM","JNPR","KSU","K","KEY","KMB","KIM","KMI","KLAC","KSS","KHC","KR","LB","LLL","LH","LRCX","LEG","LEN","LUK","LLY","LNC","LKQ","LMT","L","LOW","LYB","MTB","MAC","M","MRO","MPC","MAR","MMC","MLM","MAS","MA","MAT","MKC","MCD","MCK","MDT","MRK","MET","MTD","MGM","KORS","MCHP","MU","MSFT","MAA","MHK","TAP","MDLZ","MON","MNST","MCO","MS","MSI","MYL","NDAQ","NOV","NAVI","NKTR","NTAP","NFLX","NWL","NFX","NEM","NWSA","NWS","NEE","NLSN","NKE","NI","NBL","JWN","NSC","NTRS","NOC","NCLH","NRG","NUE","NVDA","ORLY","OXY","OMC","OKE","ORCL","PCAR","PKG","PH","PAYX","PYPL","PNR","PBCT","PEP","PKI","PRGO","PFE","PCG","PM","PSX","PNW","PXD","PNC","RL","PPG","PPL","PX","PFG","PG","PGR","PLD","PRU","PEG","PSA","PHM","PVH","QRVO","QCOM","PWR","DGX","RRC","RJF","RTN","O","RHT","REG","REGN","RF","RSG","RMD","RHI","ROK","COL","ROP","ROST","RCL","SPGI","CRM","SBAC","SCG","SLB","STX","SEE","SRE","SHW","SPG","SWKS","SLG","SNA","SO","LUV","SWK","SBUX","STT","SRCL","SYK","STI","SIVB","SYMC","SYF","SNPS","SYY","TROW","TTWO","TPR","TGT","TEL","FTI","TXN","TXT","BK","CLX","COO","HSY","MOS","TRV","DIS","TMO","TIF","TWX","TJX","TMK","TSS","TSCO","TDG","TRIP","FOXA","FOX","TSN","USB","UDR","ULTA","UAA","UA","UNP","UAL","UNH","UPS","URI","UTX","UHS","UNM","VFC","VLO","VAR","VTR","VRSN","VRSK","VZ","VRTX","VIAB","V","VNO","VMC","WMT","WBA","WM","WAT","WEC","WFC","WELL","WDC","WU","WRK","WY","WHR","WMB","WLTW","WYN","WYNN","XEL","XRX","XLNX","XL","XYL","YUM","ZBH","ZION","ZTS")
#companies <- c("ANOD-B.ST", "ANOT.ST", "B3.ST", "BELE.ST", "BETCO.ST", "DOM.ST", "DORO.ST", "DUST.ST", "EDGE.ST", "ERIC-A.ST", "ERIC-B.ST", "FING-B.ST", "FPIP.ST", "HANZA.ST", "HEXA-B.ST", "HTRO.ST", "HIQ.ST", "HMS.ST", "IAR-B.ST", "ICTA.ST", "IS.ST", "IVSO.ST", "KNOW.ST", "LAGR-B.ST", "LIME.ST", "MEAB-B.ST", "MSAB-B.ST", "MULQ.ST", "MYCR.ST", "NCAB.ST", "NETI-B.ST", "NOTE.ST", "NTEK-B.ST", "PREV-B.ST", "PACT.ST", "SINT.ST", "SOF-B.ST", "STRAX.ST", "TIETOS.ST", "TOBII.ST", "VIT-B.ST")

#companies <- c("AUY", "ODC")
obj <- c(); 
obj_static <- c();
borsvarde <- c()
remove_index <- c()
for(i in seq_along(companies)){ 
  str1 <- paste('{"company": "', companies[[i]], '"}', sep=""); 
  df <- con$find(str1)$data; 
  if(is.null(df) == TRUE){
    remove_index <- c(remove_index, i)
  }else{
    names(df) <- companies[[i]];
  }
  obj_static <- c(obj_static, df);
};
if(is.null(remove_index) == FALSE){
  companies <- companies[-c(remove_index)]
}
len_co <- length(companies)
index <- c()
for(i in seq(companies)){
  tryCatch( {
    obj_static[[companies[[i]]]] <- obj_static[[companies[[i]]]][complete.cases(obj_static[[companies[[i]]]]), ]
    obj_static[[ companies[[i]] ]][['date']] <- as.Date(obj_static[[ companies[[i]] ]][['date']], format= "%Y-%m-%d"); 
    obj_static[[ companies[[i]] ]][['close']] <- as.numeric(obj_static[[ companies[[i]] ]][['close']]); 
    obj_static[[ companies[[i]] ]][['volume']] <- as.numeric(obj_static[[ companies[[i]] ]][['volume']]); 
    obj_static[[ companies[[i]] ]][['high']] <- as.numeric(obj_static[[ companies[[i]] ]][['high']]);
    obj_static[[ companies[[i]] ]][['low']] <- as.numeric(obj_static[[ companies[[i]] ]][['low']]);
    obj_static[[ companies[[i]] ]][['open']] <- as.numeric(obj_static[[ companies[[i]] ]][['open']]);
    obj_static[[ companies[[i]] ]] <- subset(obj_static[[ companies[[i]] ]], date >= startdate1 & date <= enddate1); 
    obj_static[[ companies[[i]] ]][['close']] <- rev(obj_static[[companies[[i]] ]][['close']]); 
    obj_static[[ companies[[i]] ]][['date']] <- rev(obj_static[[ companies[[i]] ]][['date']]); 
    obj_static[[ companies[[i]] ]][['volume']] <- rev(obj_static[[ companies[[i]] ]][['volume']])
    obj_static[[ companies[[i]] ]][['high']] <- rev(obj_static[[ companies[[i]] ]][['high']])
    obj_static[[ companies[[i]] ]][['low']] <- rev(obj_static[[ companies[[i]] ]][['low']])
    obj_static[[ companies[[i]] ]][['open']] <- rev(obj_static[[ companies[[i]] ]][['open']])
    
  }
  , error = function(e) {
    print(companies[[i]])
    print(e)
  })
  #3725
  #3740
  if( length(obj_static[[companies[[i]]]][['date']]) > length(index_market)+10 || 
      length(obj_static[[companies[[i]]]][['date']]) < length(index_market)-10){
    index <- c(index, i)
    #print(length(obj_static[[ companies[[i]] ]][['date']]))
    #print(length(obj_static[[ 2 ]][['date']]))
  }else{
    dplr <- NULL
    dplr <- left_join(obj_static1[['^GSPC']], obj_static[[companies[[i]]]], by=c("date"))
    array = c(NULL)
    if(length(dplr[['date']] ) != length(na.locf(dplr[['close.y']], fromLast = TRUE))
       || length(dplr[['date']] ) != length(na.locf(dplr[['volume.y']], fromLast = TRUE)) 
       || length(dplr[['date']] ) != length(na.locf(dplr[['high.y']], fromLast = TRUE)) 
       || length(dplr[['date']] ) != length(na.locf(dplr[['low.y']], fromLast = TRUE)) 
       || length(dplr[['date']] ) != length(na.locf(dplr[['open.y']], fromLast = TRUE)) 
       ){
      index <- c(index, i)
      next
    }
    newDataFrame = data.frame(
      date = dplr[['date']] ,
      close = c(array, na.locf(dplr[['close.y']], fromLast = TRUE) ),
      volume = c(array, na.locf(dplr[['volume.y']], fromLast = TRUE)),
      high = c(array, na.locf(dplr[['high.y']], fromLast = TRUE) ),
      low = c(array, na.locf(dplr[['low.y']], fromLast = TRUE)),
      open = c(array, na.locf(dplr[['open.y']], fromLast = TRUE))
    )
    #newDataFrame[['close']] = na.locf(newDataFrame[['close']]  , fromLast = FALSE)
    obj_static[[ companies[[i]] ]] = newDataFrame;
  }
}
if(is.null(index)== FALSE){
  obj_static <- obj_static[-c(index)]
  companies <- companies[-c(index)]
}

#for(i in seq_along(companies)){
#  if(length(obj_static[[ companies[[i]] ]][['date']]) > 4991){
#  x <- left_join(obj_static[['MMM']], obj_static[[ companies[[i]] ]], by=c("date"))
#  obj_static[[ companies[[i]] ]] <- data.frame(
#    date = x[['date']],
#    open = x[['open.y']],
#    high = x[['high.y']],
#    low = x[['low.y']],
#    close = x[['close.y']],
#    adjClose = x[['adjClose.y']],
##    volume = x[['volume.y']]
#  )
#  }
#}

## CLONE OBJ
"len <- length(obj_static[[ 'MMM' ]][['date']])

## CUT OBSERVATIONS

for(h in seq_along(obj_static)){
  obj_static[[h]] <- obj_static[[h]][(len-(3725-1)):(len),];
}
"

#from 2015, 1215
# from 2011, 2224
# from 2017, 714

get_return_old <- function(array_1, days_1, avgift = NULL){ 
  g <- c(); 
  av <- 0; 
  if(is.numeric(avgift) == TRUE ){ 
    av <- avgift; 
  }; 
  for(i in seq_along(array_1)){ 
    if(i < 1+days_1){ 
      next; 
    };
    if(i %% days_1 == 0){
      g <- c(g, ((array_1[[i]] - array_1[[i-days_1]])/array_1[[i-days_1]]) - av);
    }
  }; 
  return(g); 
}
get_return <- function(array_1, days_1, avgift = NULL){ 
  g <- c(); 
  av <- 0; 
  if(is.numeric(avgift) == TRUE ){ 
    av <- avgift; 
  };
  
  n <- length(array_1)
  for(i in seq_along(array_1)){
    if(n <= 0 || n-days_1 <= 0){
      break;
    }
    
    g <- c(g, ((array_1[[n]] - array_1[[n-days_1]])/array_1[[n-days_1]]) - av);
    
    n <- n - days_1
  }
  return(rev(g)); 
}
get_return_every_day <- function(array_1, days_1, avgift = NULL){ 
  g <- c(); 
  av <- 0; 
  if(is.numeric(avgift) == TRUE ){ 
    av <- avgift; 
  };
  
  n <- length(array_1)
  for(i in seq_along(array_1)){
    if(n <= 0 || n-days_1 <= 0){
      break;
    }
    
    g <- c(g, ((array_1[[n]] - array_1[[n-days_1]])/array_1[[n-days_1]]) - av);
    
    n <- n - 1
  }
  return(rev(g)); 
}

return_RSI_MACD_ROC_STOCH_AROON <- function(array_1, days_1, days_2, MACD_days){
  l <- list()
  g <- c()
  g2 <- c()
  g3 <- c()
  g4 <- c()
  g5 <- c()
  g6 <- c()
  g7 <- c()
  g8 <- c()
  for(i in seq_along(array_1)){
    if(i+days_1+1 > length(array_1) || i < 1+days_2 || i < 1+MACD_days || i < 1+34){
      next;
    }
    g <- c(g, mean((array_1[(i+days_1-5):((i+days_1+5))] - array_1[[i]])/array_1[[i]]));
    ## RSI
    g2 <- c(g2, RSI(array_1[(i-days_2):i], days_2-1)[[(days_2+1)]]);
    ##SIGNAL
    #g3 <- c(g3, as.numeric(MACD(array_1[(i-MACD_days):(i)])[35,2]))
    ##MACD
    #g4 <- c(g4, as.numeric(MACD(array_1[(i-MACD_days):(i)])[35,1]))
    ##ROC
    tf <- ROC(data.frame(volume=obj[[ co ]][['volume']][(i-days_2):i], close=obj[[ co ]][['close']][(i-days_2):i]))
    g5 <-  c(g5, tf[[length(tf)]])
    ##STOCH
    ##SMI
    #g6 <- c(g6, as.numeric(SMI(data.frame(high=obj[[ co ]][['high']][(i-34):i], low=obj[[ co ]][['low']][(i-34):i], close=obj[[ co ]][['close']][(i-34):i]))[35,1]))
    ##SIGNAL
    #g7 <- c(g7, as.numeric(SMI(data.frame(high=obj[[ co ]][['high']][(i-34):i], low=obj[[ co ]][['low']][(i-34):i], close=obj[[ co ]][['close']][(i-34):i]))[35,2]))
    ## AROON
    g8 <- c(g8, as.numeric(aroon(data.frame(high=obj[[ co ]][['high']][(i-22):i], low=obj[[ co ]][['low']][(i-22):i]))[[23,3]]))
  }
  l[['y']] <- g
  l[[2]] <- g2
  l[[3]] <- g3
  l[[4]] <- g4
  l[[5]] <- g5
  l[[6]] <- g6
  l[[7]] <- g7
  l[[8]] <- g8
  return(l)
}

seq_this <- function(array){
  return(seq(1:length(array)))
}

plot_this = function(array){
  plot(seq_this(array), array, type="l")
}

get_last_item <- function(array){
  return(array[[ length(array) ]]);
}

copy_companies <- companies

length(obj_static[['MSFT']][['close']])
plot_this(obj_static[['NFLX']][['close']])
length(index_market)
